/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/gajagajago/slurm_build/lib/slurm";
char *default_slurm_config_file = "/home/gajagajago/deepshare/slurm/etc/slurm.conf";
